# Generated by Django 3.1.7 on 2021-03-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('notification_type', models.IntegerField()),
                ('payload', models.JSONField()),
                ('priority', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
