# Generated by Django 3.1.7 on 2021-03-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='institution',
        ),
        migrations.AddField(
            model_name='trader',
            name='institution_id',
            field=models.UUIDField(null=True),
        ),
    ]
