# Generated by Django 3.1.7 on 2021-02-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COBOrder',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('trader_id', models.UUIDField()),
                ('isin', models.UUIDField()),
                ('submission', models.DateTimeField()),
                ('expiration', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=20, max_digits=40)),
                ('size', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('pending', 'Pending'), ('full-allocation', 'Full Allocation')], max_length=150)),
                ('dirty_price', models.DecimalField(decimal_places=20, max_digits=40)),
                ('notional', models.DecimalField(decimal_places=20, max_digits=40)),
                ('spread', models.DecimalField(blank=True, decimal_places=20, max_digits=40, null=True)),
                ('discount_margin', models.DecimalField(blank=True, decimal_places=20, max_digits=40, null=True)),
                ('yield_value', models.DecimalField(decimal_places=20, max_digits=40)),
                ('parent', models.UUIDField(null=True)),
                ('origin', models.UUIDField(null=True)),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('isin', models.CharField(max_length=24, unique=True)),
                ('open', models.BooleanField()),
            ],
        ),
    ]
