# Generated by Django 3.1.7 on 2021-03-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('isin', models.CharField(max_length=24, unique=True)),
                ('open', models.BooleanField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
