# Generated by Django 3.1.7 on 2021-03-16 20:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('isin', models.CharField(max_length=24, unique=True)),
                ('open', models.BooleanField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('security_id', models.UUIDField()),
                ('orderbook_type', models.CharField(choices=[('cob', 'COB'), ('rfq', 'RFQ')], max_length=150)),
                ('order_type', models.CharField(choices=[('stream', 'Stream')], max_length=150)),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('market', 'Market')], max_length=150)),
                ('size', models.PositiveIntegerField()),
                ('notional', models.DecimalField(decimal_places=20, max_digits=40)),
                ('weighted_avg_price', models.DecimalField(decimal_places=20, max_digits=40, null=True)),
                ('weighted_avg_yield', models.DecimalField(decimal_places=20, max_digits=40, null=True)),
                ('weighted_avg_spread', models.DecimalField(decimal_places=20, max_digits=40, null=True)),
                ('fx', models.DecimalField(decimal_places=20, max_digits=40, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('pending', 'Pending'), ('full-allocation', 'Full Allocation')], max_length=150)),
                ('allocation_pct', models.DecimalField(decimal_places=20, max_digits=40)),
                ('submission', models.DateTimeField()),
                ('priority', models.DateTimeField()),
                ('expiration', models.DateTimeField()),
                ('response_type', models.CharField(choices=[('autoresponder', 'Autoresponder'), ('manual', 'Manual')], max_length=150)),
                ('settlement_currency', models.CharField(choices=[('usd', 'US Dollars'), ('mxn', 'Mexican Peso')], max_length=150)),
                ('requestor_type', models.CharField(choices=[('anonymous', 'Anonymous'), ('not-anonymous', 'Not Anonymous')], max_length=150)),
                ('resp_received', models.PositiveIntegerField()),
                ('requestor_institution_id', models.UUIDField()),
                ('trader_id', models.UUIDField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
