# Generated by Django 3.1.7 on 2021-03-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergroup',
            old_name='requestor',
            new_name='requestor_id',
        ),
        migrations.RenameField(
            model_name='ordergroup',
            old_name='security',
            new_name='security_id',
        ),
        migrations.RenameField(
            model_name='ordergroup',
            old_name='trader',
            new_name='trader_id',
        ),
    ]
