# Generated by Django 3.1.7 on 2021-03-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20210317_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergroup',
            name='order_type',
            field=models.CharField(choices=[('stream', 'COB Stream'), ('cob-market', 'COB Market'), ('cob-limit', 'COB Limit'), ('rfq', 'RFQ')], max_length=150),
        ),
    ]
