# Generated by Django 3.1.7 on 2021-03-16 00:35

import django.contrib.postgres.fields
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityIssuer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isin', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('ticker', models.CharField(max_length=250)),
                ('series', models.CharField(max_length=250, unique=True)),
                ('registration', models.CharField(choices=[('cnbv', 'CNBV'), ('144a', '144A'), ('reg-s', 'RegS'), ('sec-reg', 'SEC-Reg'), ('mex-pp', 'Mex PP'), ('sov', 'Sov'), ('sov-gtee', 'Sov Gtee')], max_length=250)),
                ('classification_mx', models.CharField(max_length=250)),
                ('amortization_scheme', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('coupon_rate', models.DecimalField(decimal_places=20, max_digits=40)),
                ('initial_margin', models.DecimalField(decimal_places=20, max_digits=40)),
                ('issue_date', models.DateTimeField()),
                ('first_coupon_date', models.DateTimeField()),
                ('final_maturity_date', models.DateTimeField()),
                ('nominal_value', models.DecimalField(decimal_places=20, max_digits=40)),
                ('year_day_count', models.IntegerField()),
                ('redemption_price', models.DecimalField(decimal_places=20, max_digits=40)),
                ('security_notes', models.CharField(max_length=250)),
                ('number_of_payments', models.PositiveIntegerField()),
                ('issued_amount', models.DecimalField(decimal_places=20, max_digits=40)),
                ('outstanding', models.DecimalField(decimal_places=20, max_digits=40)),
                ('category', models.CharField(choices=[('fixed-rate', 'Fixed Rate')], max_length=250)),
                ('listing', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('bmv', 'BMV'), ('lux', 'LUX'), ('stg', 'STG')], max_length=150), size=None)),
                ('clearing', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('indeval', 'Indeval'), ('dtc', 'DTC'), ('euroclear', 'Euroclear'), ('clearstream', 'Clearstream')], max_length=150), size=None)),
                ('amortization_structure', models.CharField(choices=[('bullet', 'Bullet'), ('amortizer', 'Amortizer'), ('soft-bullet', 'Soft bullet'), ('variable-amortizer', 'Variable amortizer')], max_length=150)),
                ('redemption_type', models.CharField(choices=[('30-day-avg', '30 day average')], max_length=150)),
                ('coupon_period', models.CharField(choices=[('7d', '7 days'), ('28d', '28 days'), ('182d', '182 days'), ('360d', '360 days')], max_length=150)),
                ('day_count_convention', models.CharField(choices=[('mx-act-360', 'MEX Conv (ACT/360)'), ('us-30-360', 'US Conv (30/360)')], max_length=150)),
                ('currency_risk', models.CharField(choices=[('usd', 'US Dollar'), ('mxn', 'Mexican Peso'), ('udi', 'UDI')], max_length=150)),
                ('currency_of_payments', models.CharField(choices=[('usd', 'US Dollars'), ('mxn', 'Mexican Peso')], max_length=150)),
                ('security_type', models.CharField(choices=[('m-bono', 'MBono'), ('mex-corp-cebur', 'Mex Corp (CEBUR)'), ('mex-corp-st-cebur-cp', 'Mex Corp St (CEBUR CP)'), ('asset-backend-cebur-f', 'Asset-Backed (CEBUR F)'), ('cete', 'CETE'), ('bonde', 'BONDE')], max_length=150)),
                ('seniority', models.CharField(choices=[('senior', 'Senior'), ('subordinate', 'Subordinate'), ('contingent-capital-at1', 'Contingent Capital AT1'), ('contingent-capital-t2', 'Contingent Capital T2')], max_length=150)),
                ('guarantee', models.CharField(choices=[('secured', 'Secured'), ('unsecured', 'Unsecured')], max_length=150)),
                ('issuer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.securityissuer')),
            ],
            options={
                'verbose_name_plural': 'Securities',
                'ordering': ['id'],
            },
        ),
    ]
