# Generated by Django 3.1.7 on 2021-02-24 07:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=100)),
                ('raw_message', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'loggers',
            },
        ),
    ]
