# Generated by Django 3.1.7 on 2021-03-16 20:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('contract', models.UUIDField()),
                ('rfc', models.CharField(max_length=350, unique=True)),
                ('logo', models.UUIDField()),
                ('status', models.CharField(choices=[('enabled', 'enabled'), ('disabled', 'disabled')], max_length=150)),
                ('demo_licenses', models.PositiveIntegerField()),
                ('trade_licenses', models.PositiveIntegerField()),
                ('data_licenses', models.PositiveIntegerField()),
                ('curp', models.CharField(max_length=50, unique=True)),
                ('compliance_officer', models.UUIDField()),
                ('address', models.UUIDField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionLicense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionManager',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SettlementInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('document', models.UUIDField()),
                ('clearing_house', models.CharField(choices=[('indeval', 'Indeval'), ('dtc', 'DTC'), ('euroclear', 'Euroclear'), ('clearstream', 'Clearstream')], max_length=250)),
                ('account', models.CharField(max_length=250)),
                ('bic_code', models.CharField(max_length=250)),
                ('custodian', models.CharField(max_length=250)),
                ('trader', models.UUIDField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], max_length=250)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RfqLock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], max_length=150)),
                ('trader_id', models.UUIDField()),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='institution',
            name='license_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institutionlicense'),
        ),
        migrations.AddField(
            model_name='institution',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institutionmanager'),
        ),
    ]
