# Generated by Django 3.1.7 on 2021-03-16 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='compliance_officer',
            new_name='compliance_officer_id',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='contract',
            new_name='contract_id',
        ),
    ]
