# Generated by Django 3.1.7 on 2021-03-16 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_auto_20210316_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='logo',
            new_name='logo_id',
        ),
    ]
