# Generated by Django 3.1.7 on 2021-03-16 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_auto_20210316_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settlementinstruction',
            old_name='document',
            new_name='document_id',
        ),
        migrations.RenameField(
            model_name='settlementinstruction',
            old_name='trader',
            new_name='trader_id',
        ),
    ]
