# Generated by Django 3.1.7 on 2021-03-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=255)),
                ('email_enabled', models.BooleanField()),
                ('ws_enabled', models.BooleanField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
