# Generated by Django 3.1.7 on 2021-03-16 22:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concierge',
            name='institution_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), null=True, size=None),
        ),
    ]
