# Generated by Django 3.1.7 on 2021-03-16 23:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zero', '0002_auto_20210316_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqresponse',
            name='counterparty_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
    ]
